### ISSUE TITLE
Support XML serialization/deserialization with XML schema

### ISSUE THREAD

**Issue by dhmlau** [strongloop/strong-soap#177]
To support serialization and deserialization of json -> xml conforming to XML schema, there are a few to-dos:
- [ ] given a xml schema, json can be converted to XML documents
    -  [ ] create an example (could be a separate repo?) that shows how to do bidirectional conversion conforming to xml schema
        - Investigate whether we can do it with no/minimal code change.  
- [ ] given a xml document and xml schema, deserialize it to json (how does it different from without xml schema case?)
